# Generated by Django 3.2.13 on 2022-06-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterData',
            fields=[
                ('twitterID', models.BigAutoField(primary_key=True, serialize=False)),
                ('twitter_url', models.URLField()),
                ('twitter_id', models.TextField(blank=True, null=True)),
                ('twitter_replies_number', models.IntegerField(default=0)),
                ('twitter_positive_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('twitter_negective_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('twitter_neutral_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('twitter_replies_texts_classification', models.TextField(blank=True, null=True)),
                ('analysis_status', models.TextField(default='Submitted')),
                ('analysis_created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_updated_at', models.DateTimeField(auto_now_add=True)),
                ('request_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
