# Generated by Django 3.2.13 on 2022-06-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetsreplyanalysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterdata',
            old_name='twitter_negective_percentage',
            new_name='twitter_negative_percentage',
        ),
    ]
