# Generated by Django 3.2.13 on 2022-06-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userFirstName', models.CharField(max_length=200)),
                ('userLastName', models.CharField(max_length=200)),
                ('userEmail', models.EmailField(max_length=300)),
                ('userPwd', models.CharField(max_length=200)),
            ],
        ),
    ]
